# Generated by Django 3.2.8 on 2021-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hashtag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
